### ISSUE TITLE
When will you open source code and publish the article?

### ISSUE THREAD

**Issue by Xuchen-Li** [jiawen-zhu/TrackGPT#1]
Happy New Year! I'm very excited to see such excellent work on the first day of the new year. Looking forward to the code and articles!

**Comment by jiawen-zhu** [comment]
Thanks~ 
Happy new year and all the best for your research as well as your life.
The code is currently under review by the company and will be open-sourced once it is approved.

**Comment by Xuchen-Li** [comment]
Thanks!✨✨
